export const ROLES = {
  STUDENT: 'STUDENT',
  INDUSTRY: 'INDUSTRY',
  ACADEMICIAN: 'ACADEMICIAN',
  INSTITUTION: 'INSTITUTION',
  ADMIN: 'ADMIN',
};

export const PROFICIENCY = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
};

export const VERIFICATION_STATUS = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};
